"""Auditable rule-demonstration warm start for recurrent HAD policies.

This module deliberately keeps imitation learning separate from reinforcement
learning.  Demonstrations are training-only trajectories generated by the
privileged (current full-state), non-oracle ``guard`` controller.  A dedicated
Adam optimizer is discarded after behavior cloning so the subsequent RL
optimizer starts with its registered, empty state.
"""

from dataclasses import asdict, dataclass
import hashlib
import json
from typing import Dict, Iterable, Mapping, Optional, Sequence, Tuple

import numpy as np
import torch
from torch import Tensor, nn
from torch.nn import functional as F

from open_score.stage1.curriculum import Scale, supported_scales
from open_score.stage1.replay import PaddedEpisodeBatch, TeamEpisode, collate_episodes
from open_score.stage1.runner import CompetitiveEpisodeRunner, RuleBasedController
from open_score.stage1.transfer import model_state_sha256


DEMONSTRATION_SEED_OFFSET = 28_000_000
DEMONSTRATION_TRAINING_SEED_STRIDE = 100_000_000
DEMONSTRATION_STYLE_STRIDE = 1_000_000
DEMONSTRATION_SCALE_STRIDE = 10_000
SUPPORTED_DEMONSTRATION_OPPONENTS = ("rush", "split_rush")


@dataclass(frozen=True)
class DemonstrationSeed:
    scale: Scale
    opponent_style: str
    episode_index: int
    seed: int


@dataclass(frozen=True)
class RuleDemonstrationDataset:
    episodes: Tuple[TeamEpisode, ...]
    metadata: Mapping[str, object]


@dataclass(frozen=True)
class ImitationMeasurement:
    cross_entropy: float
    action_accuracy: float
    active_action_count: int


def deterministic_demonstration_schedule(
    training_seed: int,
    scales: Sequence[Scale],
    opponent_styles: Sequence[str],
    episodes_per_scale_opponent: int,
) -> Tuple[DemonstrationSeed, ...]:
    """Create a collision-resistant, deterministic training-only seed grid."""

    if not 1 <= episodes_per_scale_opponent < DEMONSTRATION_SCALE_STRIDE:
        raise ValueError(
            "episodes_per_scale_opponent must be in [1, 9999] for seed isolation"
        )
    if int(training_seed) < 0:
        raise ValueError("training_seed must be non-negative")
    normalized_scales = tuple(tuple(scale) for scale in scales)
    if not normalized_scales or len(set(normalized_scales)) != len(normalized_scales):
        raise ValueError("demonstration scales must be non-empty and unique")
    if not opponent_styles or len(set(opponent_styles)) != len(opponent_styles):
        raise ValueError("demonstration opponent styles must be non-empty and unique")
    unsupported = set(opponent_styles) - set(SUPPORTED_DEMONSTRATION_OPPONENTS)
    if unsupported:
        raise ValueError(
            f"unsupported demonstration opponents: {sorted(unsupported)}"
        )
    maximum_local_seed = (
        DEMONSTRATION_SEED_OFFSET
        + (len(opponent_styles) - 1) * DEMONSTRATION_STYLE_STRIDE
        + (len(normalized_scales) - 1) * DEMONSTRATION_SCALE_STRIDE
        + episodes_per_scale_opponent
        - 1
    )
    if maximum_local_seed >= DEMONSTRATION_TRAINING_SEED_STRIDE:
        raise ValueError("demonstration grid exceeds its training-seed namespace")
    schedule = []
    for style_index, style in enumerate(opponent_styles):
        for scale_index, scale in enumerate(normalized_scales):
            for episode_index in range(episodes_per_scale_opponent):
                schedule.append(
                    DemonstrationSeed(
                        scale=scale,
                        opponent_style=style,
                        episode_index=episode_index,
                        seed=(
                            int(training_seed) * DEMONSTRATION_TRAINING_SEED_STRIDE
                            + DEMONSTRATION_SEED_OFFSET
                            + style_index * DEMONSTRATION_STYLE_STRIDE
                            + scale_index * DEMONSTRATION_SCALE_STRIDE
                            + episode_index
                        ),
                    )
                )
    seeds = [record.seed for record in schedule]
    if len(seeds) != len(set(seeds)):  # pragma: no cover - protected by strides
        raise AssertionError("demonstration seed schedule contains a collision")
    return tuple(schedule)


def evaluation_seed_set(
    base_seed: int,
    scales: Sequence[Scale],
    opponent_styles: Sequence[str],
    episodes_per_scale: int,
) -> frozenset[int]:
    """Mirror ``controlled_evaluation_suite`` exactly for leakage audits."""

    if episodes_per_scale < 1:
        raise ValueError("episodes_per_scale must be positive")
    seeds = set()
    episodes_per_style = len(scales) * episodes_per_scale
    if episodes_per_style >= 100_000:
        raise ValueError("evaluation seed cells exceed the registered style stride")
    for style_index, _ in enumerate(opponent_styles):
        style_base = int(base_seed) + style_index * 100_000
        seeds.update(style_base + index for index in range(episodes_per_style))
    return frozenset(seeds)


def audit_demonstration_seed_isolation(
    schedule: Sequence[DemonstrationSeed],
    reserved_splits: Mapping[str, Iterable[int]],
) -> Dict[str, object]:
    """Fail closed if any demonstration seed appears in a reserved split."""

    demonstration_seeds = {record.seed for record in schedule}
    overlaps: Dict[str, list[int]] = {}
    reserved_counts: Dict[str, int] = {}
    for split, values in reserved_splits.items():
        reserved = {int(value) for value in values}
        reserved_counts[str(split)] = len(reserved)
        overlap = sorted(demonstration_seeds & reserved)
        if overlap:
            overlaps[str(split)] = overlap
    passed = not overlaps
    audit = {
        "passed": passed,
        "demonstration_split": "train_only",
        "demonstration_seed_count": len(demonstration_seeds),
        "reserved_seed_counts": reserved_counts,
        "overlaps": overlaps,
    }
    if not passed:
        raise ValueError(f"demonstration seed leakage detected: {overlaps}")
    return audit


def _schedule_sha256(schedule: Sequence[DemonstrationSeed]) -> str:
    payload = [asdict(record) for record in schedule]
    encoded = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode(
        "utf-8"
    )
    return hashlib.sha256(encoded).hexdigest()


def collect_guard_demonstrations(
    runner: CompetitiveEpisodeRunner,
    scales: Sequence[Scale],
    opponent_styles: Sequence[str],
    episodes_per_scale_opponent: int,
    training_seed: int,
    reserved_splits: Optional[Mapping[str, Iterable[int]]] = None,
) -> RuleDemonstrationDataset:
    """Collect balanced Red ``guard`` trajectories against attack rules."""

    schedule = deterministic_demonstration_schedule(
        training_seed,
        scales,
        opponent_styles,
        episodes_per_scale_opponent,
    )
    seed_audit = audit_demonstration_seed_isolation(
        schedule, reserved_splits or {}
    )
    teacher = RuleBasedController("guard")
    opponents = {
        style: RuleBasedController(style) for style in opponent_styles
    }
    episodes = []
    outcomes = []
    cell_episode_counts: Dict[str, int] = {}
    cell_step_counts: Dict[str, int] = {}
    for record in schedule:
        rollout = runner.run(
            record.scale,
            teacher,
            opponents[record.opponent_style],
            record.seed,
        )
        if rollout.red.seed != record.seed:
            raise AssertionError("runner did not preserve the registered demo seed")
        episode = rollout.red
        episodes.append(episode)
        outcomes.append(float(rollout.outcome_red))
        cell = f"{record.scale[0]}v{record.scale[1]}:{record.opponent_style}"
        cell_episode_counts[cell] = cell_episode_counts.get(cell, 0) + 1
        cell_step_counts[cell] = cell_step_counts.get(cell, 0) + episode.length

    expected_cells = len(scales) * len(opponent_styles)
    if len(cell_episode_counts) != expected_cells or any(
        count != episodes_per_scale_opponent
        for count in cell_episode_counts.values()
    ):
        raise AssertionError("demonstration collection lost per-cell balance")
    registered = {tuple(scale) for scale in supported_scales(4, 1)}
    metadata: Dict[str, object] = {
        "schema_version": "had-rule-demonstrations-v1",
        "split": "train_only",
        "teacher": "rule:guard",
        "teacher_information_scope": (
            "privileged_current_HAD_engine_full_state; non-oracle; no future state, "
            "return, or heldout outcome access"
        ),
        "teacher_is_performance_upper_bound": False,
        "controlled_side": "Red",
        "opponent_styles": list(opponent_styles),
        "registered_scales": [list(scale) for scale in scales],
        "covers_all_six_registered_scales": {
            tuple(scale) for scale in scales
        }
        == registered,
        "sampling": "equal episode count in every scale-by-opponent cell",
        "episodes_per_scale_opponent": episodes_per_scale_opponent,
        "episode_count": len(episodes),
        "environment_step_count": int(sum(episode.length for episode in episodes)),
        "active_teacher_action_count": int(
            sum(
                int(observation["agent_mask"].sum())
                for episode in episodes
                for observation in episode.observations[:-1]
            )
        ),
        "cell_episode_counts": dict(sorted(cell_episode_counts.items())),
        "cell_step_counts": dict(sorted(cell_step_counts.items())),
        "teacher_mean_outcome_red": float(np.mean(outcomes)),
        "teacher_win_rate": float(np.mean(np.asarray(outcomes) > 0.0)),
        "seed_protocol": {
            "training_seed": int(training_seed),
            "training_seed_stride": DEMONSTRATION_TRAINING_SEED_STRIDE,
            "offset": DEMONSTRATION_SEED_OFFSET,
            "style_stride": DEMONSTRATION_STYLE_STRIDE,
            "scale_stride": DEMONSTRATION_SCALE_STRIDE,
            "schedule_sha256": _schedule_sha256(schedule),
            "minimum_seed": min(record.seed for record in schedule),
            "maximum_seed": max(record.seed for record in schedule),
            "records": [asdict(record) for record in schedule],
        },
        "seed_isolation_audit": seed_audit,
    }
    return RuleDemonstrationDataset(tuple(episodes), metadata)


def _policy_module(model: nn.Module, algorithm: str) -> nn.Module:
    if algorithm in {"qmix", "vdn"}:
        policy = getattr(model, "agent", None)
    elif algorithm == "mappo":
        policy = getattr(model, "actor", None)
    else:
        raise ValueError("algorithm must be qmix, vdn, or mappo")
    if not isinstance(policy, nn.Module):
        raise TypeError(f"{algorithm} model does not expose its recurrent policy")
    return policy


def recurrent_imitation_objective(
    model: nn.Module,
    algorithm: str,
    batch: PaddedEpisodeBatch,
) -> Tuple[Tensor, int, int]:
    """Return masked sequence CE, correct count and active action count.

    Hidden state is propagated from the first observation through the complete
    padded trajectory.  ``filled`` excludes padded timesteps and ``agent_mask``
    excludes destroyed/padded roster slots, so no synthetic label contributes.
    """

    hidden: Optional[Tensor] = None
    total_loss: Optional[Tensor] = None
    correct = 0
    active_action_count = 0
    for time_index in range(batch.max_steps):
        observation = batch.observation_at(time_index)
        if algorithm == "mappo":
            logits, hidden = model.actor_logits(observation, hidden)
        elif algorithm in {"qmix", "vdn"}:
            logits, hidden = model.agent_q(observation, hidden)
        else:
            raise ValueError("algorithm must be qmix, vdn, or mappo")
        targets = batch.actions[:, time_index]
        valid = (
            batch.filled[:, time_index].bool().unsqueeze(-1)
            & observation.agent_mask.bool()
        )
        target_available = observation.avail_actions.gather(
            -1, targets.unsqueeze(-1)
        ).squeeze(-1)
        if bool((valid & ~target_available.bool()).any()):
            raise ValueError("a demonstration contains an unavailable teacher action")
        if not bool(valid.any()):
            continue
        selected_logits = logits[valid]
        selected_targets = targets[valid]
        step_loss = F.cross_entropy(
            selected_logits, selected_targets, reduction="sum"
        )
        total_loss = step_loss if total_loss is None else total_loss + step_loss
        correct += int((selected_logits.argmax(dim=-1) == selected_targets).sum())
        active_action_count += int(selected_targets.numel())
    if total_loss is None or active_action_count < 1:
        raise ValueError("demonstrations contain no active teacher actions")
    return total_loss / active_action_count, correct, active_action_count


@torch.no_grad()
def measure_recurrent_imitation(
    model: nn.Module,
    algorithm: str,
    episodes: Sequence[TeamEpisode],
    batch_size: int,
    device: torch.device,
) -> ImitationMeasurement:
    if not episodes or batch_size < 1:
        raise ValueError("imitation measurement needs episodes and a positive batch")
    model.eval()
    loss_sum = 0.0
    correct = 0
    action_count = 0
    for start in range(0, len(episodes), batch_size):
        batch = collate_episodes(episodes[start : start + batch_size], device)
        loss, batch_correct, batch_count = recurrent_imitation_objective(
            model, algorithm, batch
        )
        loss_sum += float(loss.detach().cpu()) * batch_count
        correct += batch_correct
        action_count += batch_count
    return ImitationMeasurement(
        cross_entropy=loss_sum / action_count,
        action_accuracy=correct / action_count,
        active_action_count=action_count,
    )


def train_recurrent_behavior_clone(
    model: nn.Module,
    algorithm: str,
    episodes: Sequence[TeamEpisode],
    *,
    epochs: int,
    batch_size: int,
    learning_rate: float,
    shuffle_seed: int,
    device: torch.device,
    max_grad_norm: float = 10.0,
) -> Dict[str, object]:
    """Warm-start a recurrent policy with full-trajectory masked CE."""

    if not episodes:
        raise ValueError("behavior cloning needs at least one demonstration")
    if epochs < 1 or batch_size < 1 or learning_rate <= 0.0:
        raise ValueError("epochs, batch_size and learning_rate must be positive")
    policy = _policy_module(model, algorithm)
    pre_model_hash = model_state_sha256(model.state_dict())
    pre_policy_hash = model_state_sha256(policy.state_dict())
    before = measure_recurrent_imitation(
        model, algorithm, episodes, batch_size, device
    )
    optimizer = torch.optim.Adam(policy.parameters(), lr=learning_rate)
    rng = np.random.default_rng(int(shuffle_seed))
    epoch_metrics = []
    optimizer_steps = 0
    maximum_grad_norm = 0.0
    for epoch_index in range(epochs):
        ordering = rng.permutation(len(episodes))
        epoch_loss_sum = 0.0
        epoch_correct = 0
        epoch_action_count = 0
        for start in range(0, len(episodes), batch_size):
            indices = ordering[start : start + batch_size]
            batch = collate_episodes(
                [episodes[int(index)] for index in indices], device
            )
            model.train()
            loss, correct, action_count = recurrent_imitation_objective(
                model, algorithm, batch
            )
            optimizer.zero_grad(set_to_none=True)
            loss.backward()
            grad_norm = torch.nn.utils.clip_grad_norm_(
                policy.parameters(), max_grad_norm
            )
            optimizer.step()
            optimizer_steps += 1
            maximum_grad_norm = max(
                maximum_grad_norm, float(torch.as_tensor(grad_norm).detach().cpu())
            )
            epoch_loss_sum += float(loss.detach().cpu()) * action_count
            epoch_correct += correct
            epoch_action_count += action_count
        epoch_metrics.append(
            {
                "epoch": epoch_index + 1,
                "online_minibatch_cross_entropy": (
                    epoch_loss_sum / epoch_action_count
                ),
                "online_minibatch_action_accuracy": (
                    epoch_correct / epoch_action_count
                ),
                "active_action_count": epoch_action_count,
            }
        )
    after = measure_recurrent_imitation(
        model, algorithm, episodes, batch_size, device
    )
    post_model_hash = model_state_sha256(model.state_dict())
    post_policy_hash = model_state_sha256(policy.state_dict())
    return {
        "schema_version": "had-recurrent-behavior-cloning-v1",
        "enabled": True,
        "policy_training_regime": "rule_demonstration_bc_then_rl",
        "honest_label": "hybrid_rule_demonstration_pretraining_plus_RL_finetuning",
        "algorithm": algorithm,
        "sequence_semantics": (
            "full-episode recurrent BPTT; filled masks padded time; agent_mask "
            "masks destroyed and padded roster slots"
        ),
        "objective": "active-agent teacher-action categorical cross_entropy",
        "training_accuracy_is_heldout_evidence": False,
        "epochs": epochs,
        "batch_episodes": batch_size,
        "learning_rate": learning_rate,
        "shuffle_seed": int(shuffle_seed),
        "optimizer": {
            "class": "torch.optim.Adam",
            "parameter_scope": "shared recurrent agent" if algorithm != "mappo" else "actor_only",
            "optimizer_steps": optimizer_steps,
            "state_after_pretraining": "discarded",
            "rl_optimizer_semantics": "separate fresh registered RL optimizer",
        },
        "maximum_unclipped_gradient_norm": maximum_grad_norm,
        "pretraining_measurement": asdict(before),
        "posttraining_measurement": asdict(after),
        "pre_model_sha256": pre_model_hash,
        "post_model_sha256": post_model_hash,
        "pre_policy_sha256": pre_policy_hash,
        "post_policy_sha256": post_policy_hash,
        "parameters_changed": post_policy_hash != pre_policy_hash,
        "epoch_metrics": epoch_metrics,
    }


def synchronize_q_target_after_behavior_cloning(learner: object) -> Dict[str, object]:
    """Synchronize QMIX/VDN targets once, without advancing RL learner_step."""

    online = getattr(learner, "online", None)
    target = getattr(learner, "target", None)
    if not isinstance(online, nn.Module) or not isinstance(target, nn.Module):
        raise TypeError("Q-learning BC target sync requires online and target modules")
    learner_step_before = int(getattr(learner, "learner_step"))
    target_before = model_state_sha256(target.state_dict())
    target.load_state_dict(online.state_dict(), strict=True)
    target_after = model_state_sha256(target.state_dict())
    online_after = model_state_sha256(online.state_dict())
    learner_step_after = int(getattr(learner, "learner_step"))
    if learner_step_after != learner_step_before:
        raise AssertionError("BC target synchronization advanced the RL learner step")
    if target_after != online_after:
        raise AssertionError("BC target synchronization did not produce equality")
    return {
        "performed": True,
        "semantics": "hard online-to-target sync immediately after BC and before RL",
        "target_sha256_before": target_before,
        "target_sha256_after": target_after,
        "online_sha256_after": online_after,
        "online_target_equal_after": True,
        "rl_learner_step_before": learner_step_before,
        "rl_learner_step_after": learner_step_after,
    }
